language: ruby
rvm: 2.3.5
cache:
  bundler: true
before_install:
 - gem update --system
 - gem update bundler
install:
  - bundle install --jobs=3 --retry=3 --deployment --without=development --path=${BUNDLE_PATH:-vendor/bundle}
notifications:
  email: false
